# Generated by Django 3.1.5 on 2021-01-27 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeorder',
            name='warehouse_order_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='storeorder',
            name='order_number',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='warehouseaccount',
            name='warehouse_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
