# Generated by Django 3.1.5 on 2021-01-28 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StoreAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=255, unique=True)),
                ('end_point', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='WarehouseOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('IN_PROCESS', 'In Process'), ('STORED', 'Stored'), ('SEND', 'Send')], max_length=25)),
                ('store_order_id', models.PositiveIntegerField(blank=True, null=True)),
                ('store_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse_order.storeaccount')),
            ],
        ),
    ]
